---
- hosts: elkrh7
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_65_ansiblecheck"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"

  become: yes
  become_method: sudo
  tasks:
    - name: install libselinux-python
#     become: yes
#     become_method: sudo
      yum:
        name: libselinux-python
        state: present
    - name: create directory
      file:
        path: /opt/oarcle
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create dir1
      file: 
        path: /opt/oracle/jdk1.8.0_131
        state: directory
        owner: root
        group: root
        mode: 0755

    
    - name: download java 8
      get_url: url={{ download_url }} dest={{ java_archive }} headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no owner=root group=root mode=744 
    - name: unpack archive
      file: state=directory path={{java_name}} owner=root group=root recurse=yes
    - name: update alternatives
      command: alternatives --install /usr/bin/java java {{ java_name }}/bin/java 50

#     command: wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.rpm"
#     get_url:
#       url:  http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.rpm
#       dest: /opt
#       headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    - name: import ElasticSearch Key
      command: rpm --import http://packages.elastic.co/GPG-KEY-elasticsearch
    - name: create new yum repository file for ElasticSearch
      command: echo '[elasticsearch-2.x]\nname=Elasticsearch repository for 2.x packages\nbaseurl=http://packages.elastic.co/elasticsearch/2.x/centos\ngpgcheck=1\ngpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch\nenabled=1' | sudo tee /etc/yum.repos.d/elasticsearch.repo
    - name: install ElasticSearch
      command: yum -y install elasticsearch
#     yum:
#       name: 
